library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(readr)
library(jsonlite)
library(here)

i_am("Studies/Study2/Code/S2_DataProcessing.R")

cond_dict <- c(
  "0" = "Flat",
  "1" = "Increasing"
)

# Loading data
game_data <- readRDS(here("Studies/Study2", "Data", "game_choices_raw.rds"))
  

game_data <- game_data %>%
  filter(nchar(choices) != 2) %>%
  mutate(
    # Convert the JSON strings in "choices" to R lists
    choices_list = lapply(choices, fromJSON),
    # Convert the JSON strings in "choicestimes" to R lists
    times_list   = lapply(choicestimes, fromJSON)
  )

df_time_long <- game_data %>%
  # We only need turkid and times_list for the time data,
  # plus any ID columns you need to merge later (e.g., turkid, condition, etc.)
  dplyr::select(turkid, condid, condition, times_list, startdate, enddate) %>%
  # unnest_longer(...) will replicate rows for each element of times_list
  unnest_longer(
    col = times_list,
    indices_include = TRUE,
    names_repair = "minimal"
  ) %>%
  # The .id from unnest_longer will be stored in times_list_id
  rename(round = times_list_id) %>%
  mutate(
    # Convert from ms to POSIXct
    timing = as.POSIXct(
      as.numeric(times_list) / 1000,
      origin = "1970-01-01"
    ),
    round = as.integer(round)
  ) %>%
  dplyr::select(-times_list)

df_choices_long <- game_data %>%
  dplyr::select(turkid, choices_list) %>%
  unnest_longer(
    col = choices_list,
    indices_include = TRUE,
    names_repair = "minimal"
  ) %>%
  rename(
    round = choices_list_id,
    choice = choices_list
  ) %>%
  mutate(
    round = as.integer(round)
  )

game_data_clean <- df_choices_long %>%
  left_join(df_time_long, by = join_by(turkid, round)) %>%
  group_by(turkid) %>%
  mutate(
    time_to_choose = difftime(timing, lag(timing), units = "sec") %>%
      as.numeric() %>%
      replace_na(0),
    time_to_completion = difftime(enddate, startdate, units = "sec")
  )

# Save cleaned data
write_csv(game_data_clean, here("Studies/Study2", "Data", "game_choices_clean.csv"))


attributes_data <- read_csv(here("Materials", "game_attributes.csv")) %>%
  mutate(
    customers = as.integer(gsub(",", "", customers)),
    project = as.integer(substring(project, nchar(project))) - 1
  )

# Prepare df_choices
choices_data_clean <- game_data_clean %>%
  mutate(
    ones = 1,
    project = choice
  ) %>%
  pivot_wider(
    names_from = project,
    values_from = ones,
    values_fill = 0
  ) %>%
  pivot_longer(
    cols = c("2", "0", "1"),
    names_to = "project",
    values_to = "project_chosen"
  ) %>%
  mutate(project = as.integer(project)) %>%
  left_join(attributes_data, by = c("project", "round")) %>%
  janitor::clean_names()

# Save the resulting data frame
write_csv(choices_data_clean, here("Studies/Study2", "Data", "game_choices_clean_with_attributes.csv"))


cols_post <- c(
  "Duration_Post",
  "StartDate_Post",
  "EndDate_Post",
  "CouldLearn_1",
  "CouldLearn_2",
  "CouldLearn_3",
  "Confidence_NC",
  "Confidence_MS",
  "Confidence_CV",
  "Slope",
  "turkid",
  "condid"
)

survey_data_post <- read_csv(here("Data", "survey_post_raw.csv")) %>%
  rename(
    Duration_Post = `Duration (in seconds)`,
    StartDate_Post = `StartDate`,
    EndDate_Post = `EndDate`
  ) %>%
  dplyr::select(any_of(cols_post))

survey_data <- survey_data_post %>% 
  drop_na("CouldLearn_1") %>% 
  distinct(turkid, .keep_all=TRUE)  %>% 
  head(400) %>% 
  write_csv(here("Studies/Study2", "Data", "survey_clean.csv"))


# ==============================================================================
# CODEBOOK GENERATION
# Auto-generated codebook for processed data
# Generated by Qualtrics Codebook Generator
# ==============================================================================

codebook <- tibble::tribble(
  ~variable, ~description,
  "Duration_Post", "Post-survey duration in seconds (renamed from \"Duration (in seconds)\")",
  "StartDate_Post", "Post-survey start timestamp (renamed from \"StartDate\")",
  "EndDate_Post", "Post-survey end timestamp (renamed from \"EndDate\")",
  "CouldLearn_1", "I managed to learn which characteristics of companies (if any) had an impact on the ROI they generated (-2=Strongly disagree to 2=Strongly agree)",
  "CouldLearn_2", "I understood how the characteristics of companies relate to their ROIs (-2=Strongly disagree to 2=Strongly agree)",
  "CouldLearn_3", "I know which characteristics of companies affected their ROIs, and in which direction (-2=Strongly disagree to 2=Strongly agree)",
  "Confidence_NC", "During the game... a larger Number of Competitors had a NEGATIVE impact on the ROI (1=Not at all confident to 5=Extremely confident)",
  "Confidence_MS", "During the game... a larger Market Size had a POSITIVE impact on the ROI (1=Not at all confident to 5=Extremely confident)",
  "Confidence_CV", "During the game... a larger Company Valuation had a POSITIVE impact on the ROI (1=Not at all confident to 5=Extremely confident)",
  "Slope", "What do you think was true during the game you played? (1=The ROI tended to increase over time independently of which company I decided to invest in, 2=The ROI tended to stay constant over time independently of which company I decided to invest in)",
  "turkid", "Participant ID (embedded data field)",
  "condid", "Experimental condition ID (0=Flat ROI trend, 1=Increasing ROI trend)"
)

write_csv(codebook, here("Studies/Study2", "Data", "survey_codebook.csv"))

cat("\nCodebook generated with", nrow(codebook), "variables\n")
cat("Saved to: Studies/Study2/Data/survey_codebook.csv\n")
