---
title: "Appendix F - Full Results for Study 3b"
format:
  html:
    code-fold: true
    code-summary: "Show Code"
  pdf:
    toc: false
    number-sections: false

execute:
  warning: false
  message: false
  error: false
  fig-width: 10
  fig-height: 4
  fig-dpi: 400
knitr:
  opts_chunk:
    collapse: true
---
## Preamble: Data Loadings and Wrangling

```{r}
library(tidyverse)
library(tidymodels)
library(glue)
library(lme4)
library(lmerTest)
library(forcats)
library(gt)
library(gtsummary)
library(broom) # For tidy and glance functions
library(broom.mixed)
library(dplyr) # For slice and pull functions
library(here)

i_am("Appendices/AppendixF.qmd")
source(here("custom_theme.R"))

# Declare global variables to suppress warnings
globalVariables(c("statistic", "p.value"))

generate_title <- function(model) {
  coeffs <- model %>% tidy()
  summ <- model %>% glance()
  df <- summ %>% slice(1) %>% pull(df.residual)
  t <- coeffs %>% slice(2) %>% pull(statistic)
  pval <- coeffs %>% slice(2) %>% pull(p.value)
  glue(
    "t({df}) = {round(t, 3)}, {ifelse(pval < .001,
    'p < .001', glue('p = {round(pval, 3)}'))}"
  )
}

# Data loading
game_data <- read_csv(here("Studies/Study3b", "Data", "game_data_clean.csv")) %>%
  mutate(condition = factor(condition, levels = c("Flat", "Increasing")))
```

## Analysis of Choices During the Game

### Number of Attribute Changes

#### Descriptive Statistics

```{r}
game_data %>%
  filter(week != 1) %>%
  group_by(condition, week) %>%
  summarise(
    mean = mean(n_changed)
  ) %>%
  ungroup() %>%
  pivot_wider(names_from=condition, values_from=mean) %>%
  gt() %>%
  fmt_number(columns = c(Flat, Increasing)) %>%
  tab_spanner(label = "Mean Number of Attribute Changes",
              columns=c(Flat, Increasing)) %>%
  cols_label(
    week = "Round", Flat = "Flat", Increasing="Increasing",
  ) %>%
  cols_align("center", columns=c(Flat, Increasing)) %>%
  as_raw_html()
```

#### Graph
```{r}
game_data %>%
  filter(week != 1) %>%
  ggplot(aes(
    x = week, y = n_changed, fill = condition,
    shape = condition, color = condition
  )) +
  stat_summary(
    fun = mean, geom = "point",
    position = position_dodge(width = 0.5), size = 4
  ) +
  stat_summary(
    fun.data = mean_cl_boot, geom = "errorbar", width = 0,
    position = position_dodge(width = 0.5), show.legend = FALSE, size = 1.2
  ) +
  geom_smooth(
    method = "lm", alpha = 0.1, linetype = 0, span = .5, show.legend = FALSE
  ) +
  geom_line(
    stat = "smooth", method = "lm", linetype = "dashed",
    alpha = .5, show.legend = FALSE
  ) +
  labs(
    y = "Number of Attributes Changed", x = element_blank(),
    color = "Trend", fill = "Trend", shape = "Trend"
  ) +
  scale_x_continuous(
    breaks = seq(2, 8, 1),
    labels = glue("Week {seq(1, 7)}\nto {seq(2, 8)}")
  ) +
  theme_matplotlib() +
  scale_color_manual(values = c("#1f1e1e", "#3f69c9")) +
  scale_fill_manual(values = c("#1f1e1e", "#3f69c9")) +
  scale_shape_manual(values = c(21, 24))
```

#### Model Results

```{r}
lmer(
  formula = n_changed ~ week * condition + (1 + week | turkid),
  data = game_data %>% filter(week != 1)
) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  dplyr::select(-c(effect, group)) %>%
  mutate(term =
           c("Intercept", "Round", "Increasing", "Round x Increasing")
         ) %>%
  gt(rowname_col = "term") %>%
  fmt_number(columns = c(estimate, std.error, statistic, df)) %>%
  fmt(columns = p.value, fns = style_pvalue) %>%
  cols_label(
    estimate = "Estimate", std.error = "Std. Error", statistic="Statistic",
    df = "DF"
  ) %>%
  as_raw_html()
```


### Match to Best and Worst Practices

```{r}
data_cue_matches <- game_data %>%
  dplyr::select(
    c(turkid, condition, week, n_matching_best, n_matching_worst)
    ) %>%
  pivot_longer(
    cols = c(n_matching_best, n_matching_worst),
    values_to = "n_matches"
  ) %>%
  mutate(
    feature_type = glue(
    '{str_to_title(gsub("n_matching_", "", name))} Practices')
    ) %>%
  mutate(condition = factor(condition, levels = c("Flat", "Increasing")))
```

#### Descriptives

```{r}
data_cue_matches %>%
  group_by(feature_type, week, condition) %>%
  summarise(
    mean = mean(n_matches)
  ) %>%
  ungroup() %>%
  pivot_wider(
    names_from=c(feature_type, condition),
    values_from=mean
    ) %>%
  gt() %>%
  fmt_number(
    columns = c(`Best Practices_Flat`, `Best Practices_Increasing`,
                `Worst Practices_Flat`, `Worst Practices_Increasing`)
    ) %>%
  tab_spanner(label = "Cues Matching 'Best Practices'",
              columns=c(`Best Practices_Flat`, `Best Practices_Increasing`)
              ) %>%
    tab_spanner(label = "Cues Matching 'Worst Practices'",
              columns=c(`Worst Practices_Flat`, `Worst Practices_Increasing`)
              ) %>%
  cols_label(
    week = "Round", `Best Practices_Flat` = "Flat",
    `Worst Practices_Flat` = "Flat",
    `Best Practices_Increasing`="Increasing",
    `Worst Practices_Increasing`="Increasing",
  ) %>%
  cols_align("center",
             columns=c(`Best Practices_Flat`,
                       `Worst Practices_Flat`,
                       `Best Practices_Increasing`,
                       `Worst Practices_Increasing`
                       )
             ) %>%
  as_raw_html()
```

#### Graph

```{r}
data_cue_matches %>%
  mutate(condition = fct_relevel(condition, "Increasing", "Flat")) %>%
  ggplot(aes(
    x = week, y = n_matches, color = feature_type, fill = feature_type
  )) +
  stat_summary(
    fun = mean, geom = "point",
    position = position_dodge(width = 0.5), size = 4
  ) +
  stat_summary(
    fun.data = mean_cl_boot, geom = "errorbar", width = 0,
    position = position_dodge(width = 0.5), show.legend = FALSE, size = 1.2
  ) +
  geom_smooth(
    method = "lm", alpha = 0.1, linetype = 0, span = .5, show.legend = FALSE
  ) +
  geom_line(
    stat = "smooth", method = "lm",
    linetype = "dashed", alpha = .5, show.legend = FALSE
  ) +
  scale_x_continuous(
    breaks = seq(1, 8, 1),
    labels = glue("{seq(1, 8)}")
  ) +
  theme_matplotlib() +
  facet_wrap(
    . ~ condition, scales = "free",
    labeller = as_labeller(function(x) glue("{x} Condition"))
  ) +
  scale_shape_manual(values = c(21, 24)) +
  labs(
    y = "Number of Attributes Matching...", x = "Round",
    color = element_blank(), fill = element_blank()
  ) +
  theme(legend.position = c(.12, .85)) +
  scale_fill_manual(
    values = c("Best Practices" = "#E69F00", "Worst Practices" = "#4D4D4D")
  ) +
  scale_color_manual(
    values = c("Best Practices" = "#E69F00", "Worst Practices" = "#4D4D4D")
  ) +
  coord_cartesian(ylim = c(0.5, 3.2))
```

#### Model for Match to 'Best Practices'

```{r}
lmer(
  formula = n_matches ~ week * condition + (1 + week | turkid),
  data = data_cue_matches %>% filter(feature_type == "Best Practices")
) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  dplyr::select(-c(effect, group)) %>%
  mutate(term =
           c("Intercept", "Round", "Increasing", "Round x Increasing")
         ) %>%
  gt(rowname_col = "term") %>%
  fmt_number(columns = c(estimate, std.error, statistic, df)) %>%
  fmt(columns = p.value, fns = style_pvalue) %>%
  cols_label(
    estimate = "Estimate", std.error = "Std. Error", statistic="Statistic",
    df = "DF"
  ) %>%
  as_raw_html()
```

#### Model for Match to 'Worst Practices'

```{r}
lmer(
  formula = n_matches ~ week * condition + (1 + week | turkid),
  data = data_cue_matches %>% filter(feature_type == "Worst Practices")
) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  dplyr::select(-c(effect, group)) %>%
  mutate(term =
           c("Intercept", "Round", "Increasing", "Round x Increasing")
         ) %>%
  gt(rowname_col = "term") %>%
  fmt_number(columns = c(estimate, std.error, statistic, df)) %>%
  fmt(columns = p.value, fns = style_pvalue) %>%
  cols_label(
    estimate = "Estimate", std.error = "Std. Error", statistic="Statistic",
    df = "DF"
  ) %>%
  as_raw_html()
```

## Survey Dependent Variables

```{r}
survey_data_clean <- read_csv(here("Studies/Study3b", "Data", "survey_clean.csv")) %>%
  mutate(condition = factor(condition, levels = c("Flat", "Increasing")))
```

### Illusory Beliefs Index

```{r}
#| fig-height: 3.5

model <- lm(illusory_beliefs_index ~ condition, data = survey_data_clean)
survey_data_clean %>%
  ggplot(aes(
    x = condition, y = illusory_beliefs_index,
    color = condition
  )) +
  stat_summary(
    fun = mean, geom = "point", alpha = 1,
    position = position_dodge(width = 0.5), size = 4
  ) +
  stat_summary(
    fun.data = mean_cl_boot, geom = "errorbar", width = 0,
    position = position_dodge(width = 0.5), show.legend = FALSE, linewidth = 1.2
  ) +
  labs(
    x = element_blank(),
    y = "Illusory Beliefs Index (1-5)",
    title = generate_title(model)
  ) +
  theme_matplotlib() +
  scale_color_manual(values = c("#1f1e1e", "#3f69c9")) +
  guides(color = "none")
```

### Probability of Superiority

```{r}
#| fig-height: 3.5

model <- lm(prob_superiority ~ condition, data = survey_data_clean)
survey_data_clean %>%
  ggplot(aes(
    x = condition, y = prob_superiority,
    color = condition
  )) +
  stat_summary(
    fun = mean, geom = "point", alpha = 1,
    position = position_dodge(width = 0.5), size = 4
  ) +
  stat_summary(
    fun.data = mean_cl_boot, geom = "errorbar", width = 0,
    position = position_dodge(width = 0.5), show.legend = FALSE, linewidth = 1.2
  ) +
  labs(
    x = element_blank(),
    y = "Likelihood of 'Best'\nOutperforming 'Worst'",
    title = generate_title(model)
  ) +
  theme_matplotlib() +
  scale_color_manual(values = c("#1f1e1e", "#3f69c9")) +
  guides(color = "none")
```
